name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${ secrets.README_TOK }
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name erickahmed
          git config user.email erick2k@duck.com
          git add -A .
          git commit -m "3d graph updated"
          git push
